---
# tasks file for roles/haproxy

- name: install haproxy
  apt:
    name:
      - haproxy
    state: latest
    update_cache: no
  notify: 
    - restart haproxy

- name: Put config file in the right place
  copy:
    src: roles/haproxy/files/haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify:
    - restart haproxy