- name: Install all the usual stuff
  hosts: all
  gather_facts: yes
  become: yes
  roles:
    - base

- name: Configure SSHd
  hosts: all
  become: yes
  roles:
    - sshd

- name: Configure network with netplan
  hosts: routers
  become: yes
  roles:
    - netplan

- name: Setup netdata
  hosts: all
  become: yes
  roles:
    - netdata

- name: Setup cockpit
  hosts: all
  become: yes
  roles:
    - cockpit

- name: Setup dhcp server
  hosts: routers
  become: yes
  roles:
    - dhcp

- name: Setup iptables with ferm
  hosts: routers
  become: yes
  roles:
    - ferm