- name: Install all the usual stuff
  hosts: all
  gather_facts: yes
  become: yes
  roles:
    - base

- name: Configure SSHd
  hosts: all
  become: yes
  roles:
    - sshd

- name: Setup netdata
  hosts: all
  become: yes
  roles:
    - netdata

- name: Setup dhcp server
  hosts: routers
  become: yes
  roles:
    - dhcp

- name: Setum iptables with ferm
  hosts: routers
  become: yes
  roles:
    - ferm