---
# tasks file for roles/netdata

- name: Install netdata
  package:
    name: netdata
    state: present

- name: Enable netdata service
  systemd:
    name: netdata
    enabled: yes
    state: started

- name: Configure netdata to be available from anywhere
  lineinfile:
    path: /etc/netdata/netdata.conf
    regexp: "^bind socket to IP"
    line: "bind socket to IP = 0.0.0.0"
  notify: restart netdata
