---
# handlers file for roles/pritunl

- name: restart mongodb
  service:
    name: mongod
    state: restarted
    enabled: yes
  listen: "restart mongodb"

- name: restart pritunl
  service:
    name: pritunl
    state: restarted
    enabled: yes
  listen: "restart pritunl"

- name: wait for VPN clients
  pause:
    minutes: 1