---
# tasks file for roles/pritunl

- name: add keys for mongodb and pritunl repos
  apt_key:
      keyserver: hkp://keyserver.ubuntu.com # not required. The keyserver to retrieve key from.
      state: present # not required. choices: absent;present. Ensures that the key is present (added) or absent (revoked).
      id: 9DA31620334BD75D9DCB49F368818C72E52529D4 # not required. The identifier of the key.,Including this allows check mode to correctly report the changed state.,If specifying a subkey's id be aware that apt-key does not understand how to remove keys via a subkey id.  Specify the primary key's id instead.,This parameter is required when C(state) is set to C(absent).

- name: add keys for mongodb and pritunl repos
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com
    state: present
    id: 7568D9BB55FF9E5287D586017AE645C0CF8E292A

- name: add mongodb repo
  apt_repository:
      repo: deb https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse # required. A source string for the repository.
      state: present # not required. choices: absent;present. A source string state.
      update_cache: yes # not required. Run the equivalent of C(apt-get update) when a change occurs.  Cache updates are run after making changes.

- name: add pritunl repo
  apt_repository:
    repo: deb http://repo.pritunl.com/stable/apt bionic main
    state: present
    update_cache: yes

- name: install pritunl and mongodb
  apt:
    name:
      - pritunl
      - mongodb-org
    state: latest
    update_cache: yes
  notify: 
    - restart pritunl
    - restart mongodb
    - wait for VPN clients
