

### netplan configuration

netplan_configuration:
  network:
    ethernets:
        ens192:
            dhcp4: no
            dhcp6: no
            addresses:
            - 51.91.33.40/32
            gateway4: 51.91.33.254
            nameservers:
                addresses:
                - 1.1.1.1
            routes:
            - to: 51.91.33.254/32
              via: 0.0.0.0
              scope: link
        ens160:
            addresses:
            - 10.40.0.1/24
            dhcp4: no
            nameservers:
                addresses:
                - 1.1.1.1
                - 9.9.9.9
                search: []
    version: 2

### DHCPd configuration

dhcp_global_domain_name: internal.0x07.pl
dhcp_global_domain_name_servers:
  - 1.1.1.1
  - 9.9.9.9
dhcp_global_default_lease_time: 28800   # 8hrs
dhcp_global_max_lease_time: 43200

dhcp_subnets:
  - ip: 10.40.0.0
    netmask: 255.255.255.0
    range_begin: 10.40.0.101
    range_end: 10.40.0.200
    routers: 10.40.0.1

### FERM configuration
