- name: Set hostname
  hostname:
    name: "{{inventory_hostname}}"

- name: Disable AppArmor
  systemd:
    name: apparmor
    state: stopped
    enabled: no

- name: Disable fucking IPv6
  sysctl: 
    name: "{{ item }}" 
    value: "1" 
    state: present
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: Disable IPv6 DHCP
  systemd: 
    name: isc-dhcp-server6
    state: stopped
    enabled: no
  when: "'odin' in inventory_hostname"

- name: Install all the usual stuff
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes

- name: Install open-vm-tools
  become: yes
  package:
    name: open-vm-tools
    state: present

- name: disable sudo password
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'