- name: Set hostname
  hostname:
    name: "{{inventory_hostname}}"

- name: Disable AppArmor
  systemd:
    name: apparmor
    state: stopped
    enabled: no

- name: Install all the usual stuff
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes

- name: Install open-vm-tools
  become: yes
  package:
    name: open-vm-tools
    state: present

- name: disable sudo password
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'