---
# tasks file for roles/traefik


- name: Download traefik binary
  get_url:
    url: https://github.com/containous/traefik/releases/download/v2.1.4/traefik_v2.1.4_linux_amd64.tar.gz
    dest: /tmp/traefik.tar.gz

- name: Unpack traefik archive
  unarchive: 
    src: /tmp/traefik.tar.gz
    dest: /usr/bin
    mode: 0755
    group: root
    owner: root